name: Build and Release Snake BIOS

on:
  push:
    tags:
      - '*'  # Runs only when a tag is pushed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y nasm xorriso

    - name: Compile BIOS
      run: nasm bios.asm -o snake.raw

    - name: Create ISO
      run: |
        mkdir -p iso_root
        cp snake.raw iso_root/snake.raw
        xorriso -as mkisofs -o snake.iso iso_root

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload BIOS Raw File
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: snake.raw
        asset_name: snake.raw
        asset_content_type: application/octet-stream

    - name: Upload ISO File
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: snake.iso
        asset_name: snake.iso
        asset_content_type: application/octet-stream
